import os
import logging
import subprocess
from dotenv import load_dotenv
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    filters,
    ContextTypes,
)
from yt_dlp import YoutubeDL

# Update yt-dlp automatically
subprocess.run(["pip", "install", "--upgrade", "yt-dlp"], check=False)

# Load .env
load_dotenv()
TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

# Download folder
DOWNLOAD_FOLDER = "./downloads"
os.makedirs(DOWNLOAD_FOLDER, exist_ok=True)

# Logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)


# Start command
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "👋 Hello!\n"
        "Send a YouTube link\n"
        "I will send you the MP3 🎵"
    )


# Download audio from YouTube
async def download_audio(update: Update, context: ContextTypes.DEFAULT_TYPE):
    url = update.message.text.strip()

    # Validate YouTube link
    if "youtube.com" not in url and "youtu.be" not in url:
        await update.message.reply_text("❌ Please send a valid YouTube link.")
        return

    status_message = await update.message.reply_text("⏳ Downloading... please wait.")

    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": os.path.join(DOWNLOAD_FOLDER, "%(title)s.%(ext)s"),
        "quiet": True,
        "noplaylist": True,
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "192",
            }
        ],
    }

    try:
        with YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = info.get("title", "Audio")
            
            # Get the final filename generated by yt-dlp after post-processing
            filename = info.get("filepath") or os.path.join(
                DOWNLOAD_FOLDER, f"{info.get('title', 'audio')}.mp3"
            )

        # Send file
        if os.path.exists(filename):
            with open(filename, "rb") as audio:
                await update.message.reply_audio(
                    audio=audio,
                    title=title,
                )

            # Delete status message and audio file after sending
            await status_message.delete()
            os.remove(filename)
        else:
            await update.message.reply_text(
                "❌ Error: Downloaded file not found."
            )

    except Exception as e:
        logging.error(f"Download error: {e}")
        await update.message.reply_text(
            f"❌ Error downloading audio:\n{str(e)[:100]}"
        )


def main():
    if not TOKEN:
        print("❌ Add TELEGRAM_BOT_TOKEN in .env")
        return

    app = ApplicationBuilder().token(TOKEN).build()

    app.add_handler(
        CommandHandler("start", start)
    )

    app.add_handler(
        MessageHandler(
            filters.TEXT & ~filters.COMMAND,
            download_audio
        )
    )

    print("🤖 Bot running...")
    app.run_polling()


if __name__ == "__main__":
    main()
