import os
import logging
import subprocess
from dotenv import load_dotenv
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    filters,
    ContextTypes,
)
from yt_dlp import YoutubeDL

# Update yt-dlp automatically
subprocess.run(["pip", "install", "--upgrade", "yt-dlp"], check=False)

# Load .env
load_dotenv()
TOKEN = os.getenv("8825680908:AAGtIitkyTME5DA8gFGquhA6KuOqfoNSML8")

# Download folder
DOWNLOAD_FOLDER = "./downloads"
os.makedirs(DOWNLOAD_FOLDER, exist_ok=True)

# Logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)


# Start command
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "👋 Hello!\n"
        "Send a YouTube link\n"
        "I will send you the MP3 🎵"
    )


# Download audio from YouTube
async def download_audio(update: Update, context: ContextTypes.DEFAULT_TYPE):
    url = update.message.text.strip()

    # FIX 1: Corrected YouTube link validation
    if "youtube.com" not in url and "youtu.be" not in url:
        await update.message.reply_text("❌ Please send a valid YouTube link.")
        return

    status_message = await update.message.reply_text("⏳ Downloading... please wait.")

    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": f"{DOWNLOAD_FOLDER}/%(title)s.%(ext)s",
        "quiet": True,
        "noplaylist": True,
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "192",
            }
        ],
    }

    try:
        with YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = info.get("title", "Audio")
            
            # FIX 2: Safely fetch the exact final filename generated by yt-dlp
            # (yt_dlp updates requested_downloads with the final post-processed file path)
            filename = info['requested_downloads'][0]['filepath']

        # Send file
        with open(filename, "rb") as audio:
            await update.message.reply_audio(
                audio=audio,
                title=title,
            )

        # Delete status message and audio file after sending
        await status_message.delete()
        if os.path.exists(filename):
            os.remove(filename)

    except Exception as e:
        logging.error(e)
        await update.message.reply_text(
            f"❌ Error downloading audio:\n{e}"
        )


def main():
    if not TOKEN:
        print("❌ Add TELEGRAM_BOT_TOKEN in .env")
        return

    app = ApplicationBuilder().token(TOKEN).build()

    app.add_handler(
        CommandHandler("start", start)
    )

    app.add_handler(
        MessageHandler(
            filters.TEXT & ~filters.COMMAND,
            download_audio
        )
    )

    print("🤖 Bot running...")
    app.run_polling()


# FIX 3: Corrected main entry point syntax
if __name__ == "__main__":
    main()
